// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/models/epoch.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EpochStatus int32

const (
	EpochStatus_INITIATED  EpochStatus = 0
	EpochStatus_FINALIZING EpochStatus = 1
	EpochStatus_COMPLETE   EpochStatus = 2
)

var EpochStatus_name = map[int32]string{
	0: "INITIATED",
	1: "FINALIZING",
	2: "COMPLETE",
}

var EpochStatus_value = map[string]int32{
	"INITIATED":  0,
	"FINALIZING": 1,
	"COMPLETE":   2,
}

func (x EpochStatus) String() string {
	return proto.EnumName(EpochStatus_name, int32(x))
}

func (EpochStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea792eb5bd367833, []int{0}
}

type EpochSignatureMod int32

const (
	EpochSignatureMod_UNSPECIFIED_MOD EpochSignatureMod = 0
	EpochSignatureMod_ADD             EpochSignatureMod = 1
	EpochSignatureMod_REMOVE          EpochSignatureMod = 2
)

var EpochSignatureMod_name = map[int32]string{
	0: "UNSPECIFIED_MOD",
	1: "ADD",
	2: "REMOVE",
}

var EpochSignatureMod_value = map[string]int32{
	"UNSPECIFIED_MOD": 0,
	"ADD":             1,
	"REMOVE":          2,
}

func (x EpochSignatureMod) String() string {
	return proto.EnumName(EpochSignatureMod_name, int32(x))
}

func (EpochSignatureMod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea792eb5bd367833, []int{1}
}

type Epoch struct {
	Id         uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status     EpochStatus `protobuf:"varint,2,opt,name=status,proto3,enum=core.bridge.EpochStatus" json:"status,omitempty"`
	StartBlock uint64      `protobuf:"varint,3,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock   uint64      `protobuf:"varint,4,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	// store copy of params here, we do not link to params to avoid issues with params changing over time
	Parties      []*Party  `protobuf:"bytes,5,rep,name=parties,proto3" json:"parties,omitempty"`
	TssThreshold uint32    `protobuf:"varint,6,opt,name=tss_threshold,json=tssThreshold,proto3" json:"tss_threshold,omitempty"`
	TssInfo      []TSSInfo `protobuf:"bytes,7,rep,name=tss_info,json=tssInfo,proto3" json:"tss_info"`
}

func (m *Epoch) Reset()         { *m = Epoch{} }
func (m *Epoch) String() string { return proto.CompactTextString(m) }
func (*Epoch) ProtoMessage()    {}
func (*Epoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea792eb5bd367833, []int{0}
}
func (m *Epoch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Epoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Epoch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Epoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Epoch.Merge(m, src)
}
func (m *Epoch) XXX_Size() int {
	return m.Size()
}
func (m *Epoch) XXX_DiscardUnknown() {
	xxx_messageInfo_Epoch.DiscardUnknown(m)
}

var xxx_messageInfo_Epoch proto.InternalMessageInfo

func (m *Epoch) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Epoch) GetStatus() EpochStatus {
	if m != nil {
		return m.Status
	}
	return EpochStatus_INITIATED
}

func (m *Epoch) GetStartBlock() uint64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *Epoch) GetEndBlock() uint64 {
	if m != nil {
		return m.EndBlock
	}
	return 0
}

func (m *Epoch) GetParties() []*Party {
	if m != nil {
		return m.Parties
	}
	return nil
}

func (m *Epoch) GetTssThreshold() uint32 {
	if m != nil {
		return m.TssThreshold
	}
	return 0
}

func (m *Epoch) GetTssInfo() []TSSInfo {
	if m != nil {
		return m.TssInfo
	}
	return nil
}

type EpochSignature struct {
	Mod       EpochSignatureMod   `protobuf:"varint,1,opt,name=mod,proto3,enum=core.bridge.EpochSignatureMod" json:"mod,omitempty"`
	EpochId   uint32              `protobuf:"varint,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Signature string              `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Data      *EpochSignatureData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *EpochSignature) Reset()         { *m = EpochSignature{} }
func (m *EpochSignature) String() string { return proto.CompactTextString(m) }
func (*EpochSignature) ProtoMessage()    {}
func (*EpochSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea792eb5bd367833, []int{1}
}
func (m *EpochSignature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochSignature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochSignature.Merge(m, src)
}
func (m *EpochSignature) XXX_Size() int {
	return m.Size()
}
func (m *EpochSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochSignature.DiscardUnknown(m)
}

var xxx_messageInfo_EpochSignature proto.InternalMessageInfo

func (m *EpochSignature) GetMod() EpochSignatureMod {
	if m != nil {
		return m.Mod
	}
	return EpochSignatureMod_UNSPECIFIED_MOD
}

func (m *EpochSignature) GetEpochId() uint32 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *EpochSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *EpochSignature) GetData() *EpochSignatureData {
	if m != nil {
		return m.Data
	}
	return nil
}

type EpochSignatureData struct {
	NewSigner string `protobuf:"bytes,1,opt,name=new_signer,json=newSigner,proto3" json:"new_signer,omitempty"`
	StartTime uint64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   uint64 `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Nonce     string `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *EpochSignatureData) Reset()         { *m = EpochSignatureData{} }
func (m *EpochSignatureData) String() string { return proto.CompactTextString(m) }
func (*EpochSignatureData) ProtoMessage()    {}
func (*EpochSignatureData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea792eb5bd367833, []int{2}
}
func (m *EpochSignatureData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochSignatureData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochSignatureData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochSignatureData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochSignatureData.Merge(m, src)
}
func (m *EpochSignatureData) XXX_Size() int {
	return m.Size()
}
func (m *EpochSignatureData) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochSignatureData.DiscardUnknown(m)
}

var xxx_messageInfo_EpochSignatureData proto.InternalMessageInfo

func (m *EpochSignatureData) GetNewSigner() string {
	if m != nil {
		return m.NewSigner
	}
	return ""
}

func (m *EpochSignatureData) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *EpochSignatureData) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *EpochSignatureData) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type EpochChainSignatures struct {
	EpochId          uint32          `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	ChainId          string          `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AddedSignature   *EpochSignature `protobuf:"bytes,3,opt,name=added_signature,json=addedSignature,proto3" json:"added_signature,omitempty"`
	RemovedSignature *EpochSignature `protobuf:"bytes,4,opt,name=removed_signature,json=removedSignature,proto3" json:"removed_signature,omitempty"`
}

func (m *EpochChainSignatures) Reset()         { *m = EpochChainSignatures{} }
func (m *EpochChainSignatures) String() string { return proto.CompactTextString(m) }
func (*EpochChainSignatures) ProtoMessage()    {}
func (*EpochChainSignatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea792eb5bd367833, []int{3}
}
func (m *EpochChainSignatures) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochChainSignatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochChainSignatures.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochChainSignatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochChainSignatures.Merge(m, src)
}
func (m *EpochChainSignatures) XXX_Size() int {
	return m.Size()
}
func (m *EpochChainSignatures) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochChainSignatures.DiscardUnknown(m)
}

var xxx_messageInfo_EpochChainSignatures proto.InternalMessageInfo

func (m *EpochChainSignatures) GetEpochId() uint32 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *EpochChainSignatures) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *EpochChainSignatures) GetAddedSignature() *EpochSignature {
	if m != nil {
		return m.AddedSignature
	}
	return nil
}

func (m *EpochChainSignatures) GetRemovedSignature() *EpochSignature {
	if m != nil {
		return m.RemovedSignature
	}
	return nil
}

type TSSInfo struct {
	Certification string `protobuf:"bytes,1,opt,name=certification,proto3" json:"certification,omitempty"`
	Domen         string `protobuf:"bytes,2,opt,name=domen,proto3" json:"domen,omitempty"`
	Address       string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Active        bool   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *TSSInfo) Reset()         { *m = TSSInfo{} }
func (m *TSSInfo) String() string { return proto.CompactTextString(m) }
func (*TSSInfo) ProtoMessage()    {}
func (*TSSInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea792eb5bd367833, []int{4}
}
func (m *TSSInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TSSInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TSSInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TSSInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TSSInfo.Merge(m, src)
}
func (m *TSSInfo) XXX_Size() int {
	return m.Size()
}
func (m *TSSInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TSSInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TSSInfo proto.InternalMessageInfo

func (m *TSSInfo) GetCertification() string {
	if m != nil {
		return m.Certification
	}
	return ""
}

func (m *TSSInfo) GetDomen() string {
	if m != nil {
		return m.Domen
	}
	return ""
}

func (m *TSSInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TSSInfo) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func init() {
	proto.RegisterEnum("core.bridge.EpochStatus", EpochStatus_name, EpochStatus_value)
	proto.RegisterEnum("core.bridge.EpochSignatureMod", EpochSignatureMod_name, EpochSignatureMod_value)
	proto.RegisterType((*Epoch)(nil), "core.bridge.Epoch")
	proto.RegisterType((*EpochSignature)(nil), "core.bridge.EpochSignature")
	proto.RegisterType((*EpochSignatureData)(nil), "core.bridge.EpochSignatureData")
	proto.RegisterType((*EpochChainSignatures)(nil), "core.bridge.EpochChainSignatures")
	proto.RegisterType((*TSSInfo)(nil), "core.bridge.TSSInfo")
}

func init() { proto.RegisterFile("bridge/models/epoch.proto", fileDescriptor_ea792eb5bd367833) }

var fileDescriptor_ea792eb5bd367833 = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x41, 0x6f, 0x12, 0x41,
	0x14, 0x66, 0x81, 0xb2, 0xec, 0xa3, 0x50, 0x3a, 0x12, 0xb3, 0xb4, 0x4a, 0x09, 0x7a, 0x20, 0x8d,
	0xb2, 0x95, 0xc6, 0x8b, 0x89, 0x89, 0xa5, 0x6c, 0x75, 0x93, 0x42, 0xc9, 0x80, 0x1e, 0x7a, 0x21,
	0xcb, 0xce, 0x00, 0xab, 0xb0, 0x43, 0x76, 0x86, 0xd6, 0x9e, 0xfd, 0x03, 0xfa, 0x4f, 0xfc, 0x19,
	0x3d, 0xf6, 0xe8, 0xc1, 0x18, 0xd3, 0xfe, 0x11, 0xb3, 0xb3, 0x4b, 0x5b, 0xac, 0xa9, 0xb7, 0x7d,
	0xdf, 0xf7, 0xbd, 0x37, 0xdf, 0x7c, 0x6f, 0x00, 0x8a, 0x03, 0xdf, 0x25, 0x23, 0x6a, 0x4c, 0x19,
	0xa1, 0x13, 0x6e, 0xd0, 0x19, 0x73, 0xc6, 0xb5, 0x99, 0xcf, 0x04, 0x43, 0x19, 0x87, 0xf9, 0xb4,
	0x16, 0xf2, 0x1b, 0xc5, 0x11, 0x63, 0xa3, 0x09, 0x35, 0x24, 0x35, 0x98, 0x0f, 0x0d, 0xdb, 0x3b,
	0x0b, 0x75, 0x1b, 0x85, 0x11, 0x1b, 0x31, 0xf9, 0x69, 0x04, 0x5f, 0x11, 0xfa, 0xd7, 0xe0, 0x99,
	0xed, 0x8b, 0xa8, 0xa1, 0xf2, 0x2d, 0x0e, 0x2b, 0x66, 0x70, 0x10, 0xca, 0x41, 0xdc, 0x25, 0xba,
	0x52, 0x56, 0xaa, 0x59, 0x1c, 0x77, 0x09, 0xda, 0x81, 0x14, 0x17, 0xb6, 0x98, 0x73, 0x3d, 0x5e,
	0x56, 0xaa, 0xb9, 0xba, 0x5e, 0xbb, 0xe5, 0xa1, 0x26, 0x7b, 0xba, 0x92, 0xc7, 0x91, 0x0e, 0x6d,
	0x41, 0x86, 0x0b, 0xdb, 0x17, 0xfd, 0xc1, 0x84, 0x39, 0x9f, 0xf4, 0x44, 0x59, 0xa9, 0x26, 0x31,
	0x48, 0xa8, 0x11, 0x20, 0x68, 0x13, 0x34, 0xea, 0x91, 0x88, 0x4e, 0x4a, 0x3a, 0x4d, 0x3d, 0x12,
	0x92, 0xcf, 0x40, 0x0d, 0x8c, 0xb9, 0x94, 0xeb, 0x2b, 0xe5, 0x44, 0x35, 0x53, 0x47, 0x4b, 0x07,
	0x76, 0x02, 0xd3, 0x78, 0x21, 0x41, 0x4f, 0x20, 0x2b, 0x38, 0xef, 0x8b, 0xb1, 0x4f, 0xf9, 0x98,
	0x4d, 0x88, 0x9e, 0x92, 0xc6, 0x57, 0x05, 0xe7, 0xbd, 0x05, 0x86, 0x5e, 0x42, 0x3a, 0x10, 0xb9,
	0xde, 0x90, 0xe9, 0xaa, 0x9c, 0x59, 0x58, 0x9a, 0xd9, 0xeb, 0x76, 0x2d, 0x6f, 0xc8, 0x1a, 0xc9,
	0xf3, 0x5f, 0x5b, 0x31, 0xac, 0x0a, 0xce, 0x83, 0xb2, 0xf2, 0x5d, 0x81, 0x5c, 0x78, 0x3f, 0x77,
	0xe4, 0xd9, 0x62, 0xee, 0x53, 0xb4, 0x03, 0x89, 0x29, 0x0b, 0xd3, 0xc9, 0xd5, 0x4b, 0xff, 0x48,
	0x62, 0xa1, 0x6c, 0x31, 0x82, 0x03, 0x29, 0x2a, 0x42, 0x5a, 0x2e, 0xb0, 0xef, 0x12, 0x19, 0x60,
	0x16, 0xab, 0xb2, 0xb6, 0x08, 0x7a, 0x04, 0x1a, 0x5f, 0xe8, 0x65, 0x4a, 0x1a, 0xbe, 0x01, 0xd0,
	0x2e, 0x24, 0x89, 0x2d, 0x6c, 0x99, 0x4f, 0xa6, 0xbe, 0x75, 0xcf, 0x59, 0x4d, 0x5b, 0xd8, 0x58,
	0x8a, 0x2b, 0x5f, 0x14, 0x40, 0x77, 0x49, 0xf4, 0x18, 0xc0, 0xa3, 0xa7, 0xfd, 0x60, 0x38, 0xf5,
	0xa5, 0x7b, 0x0d, 0x6b, 0x1e, 0x3d, 0xed, 0x4a, 0x20, 0xa0, 0xc3, 0x85, 0x09, 0x77, 0x4a, 0xa5,
	0xcb, 0x24, 0xd6, 0x24, 0xd2, 0x73, 0xa7, 0x54, 0x5e, 0xc1, 0x23, 0x21, 0x19, 0x2e, 0x53, 0xa5,
	0x1e, 0x91, 0x54, 0x01, 0x56, 0x3c, 0xe6, 0x39, 0x54, 0xba, 0xd4, 0x70, 0x58, 0x54, 0x7e, 0x2a,
	0x50, 0x90, 0x2e, 0xf6, 0xc7, 0xb6, 0xeb, 0x5d, 0x5b, 0xe1, 0x4b, 0x61, 0x28, 0xcb, 0x61, 0x14,
	0x21, 0xed, 0x04, 0xea, 0x45, 0x4e, 0x1a, 0x56, 0x65, 0x6d, 0x11, 0xd4, 0x84, 0x35, 0x9b, 0x10,
	0x4a, 0xfa, 0xcb, 0x69, 0x65, 0xea, 0x9b, 0xf7, 0x84, 0x82, 0x73, 0xb2, 0xe7, 0x66, 0x75, 0xef,
	0x60, 0xdd, 0xa7, 0x53, 0x76, 0xb2, 0x34, 0x27, 0xf9, 0xff, 0x39, 0xf9, 0xa8, 0xeb, 0x1a, 0xa9,
	0x9c, 0x82, 0x1a, 0xbd, 0x18, 0xf4, 0x14, 0xb2, 0x0e, 0xf5, 0x85, 0x3b, 0x74, 0x1d, 0x5b, 0xb8,
	0xcc, 0x8b, 0xb2, 0x5d, 0x06, 0x83, 0x94, 0x08, 0x9b, 0x52, 0x2f, 0xba, 0x58, 0x58, 0x20, 0x1d,
	0x54, 0x9b, 0x10, 0x9f, 0x72, 0x1e, 0x2d, 0x7f, 0x51, 0xa2, 0x87, 0x90, 0xb2, 0x1d, 0xe1, 0x9e,
	0x84, 0xfe, 0xd2, 0x38, 0xaa, 0xb6, 0x5f, 0x41, 0xe6, 0xd6, 0xef, 0x0d, 0x65, 0x41, 0xb3, 0xda,
	0x56, 0xcf, 0xda, 0xeb, 0x99, 0xcd, 0x7c, 0x0c, 0xe5, 0x00, 0x0e, 0xac, 0xf6, 0xde, 0xa1, 0x75,
	0x6c, 0xb5, 0xdf, 0xe6, 0x15, 0xb4, 0x0a, 0xe9, 0xfd, 0xa3, 0x56, 0xe7, 0xd0, 0xec, 0x99, 0xf9,
	0xf8, 0xf6, 0x6b, 0x58, 0xbf, 0xf3, 0x42, 0xd1, 0x03, 0x58, 0x7b, 0xdf, 0xee, 0x76, 0xcc, 0x7d,
	0xeb, 0xc0, 0x32, 0x9b, 0xfd, 0xd6, 0x51, 0x30, 0x47, 0x85, 0xc4, 0x5e, 0xb3, 0x99, 0x57, 0x10,
	0x40, 0x0a, 0x9b, 0xad, 0xa3, 0x0f, 0x66, 0x3e, 0xde, 0x38, 0x3e, 0xbf, 0x2c, 0x29, 0x17, 0x97,
	0x25, 0xe5, 0xf7, 0x65, 0x49, 0xf9, 0x7a, 0x55, 0x8a, 0x5d, 0x5c, 0x95, 0x62, 0x3f, 0xae, 0x4a,
	0xb1, 0xe3, 0x37, 0x23, 0x57, 0x8c, 0xe7, 0x83, 0x9a, 0xc3, 0xa6, 0x46, 0x43, 0x26, 0x38, 0xa1,
	0x9c, 0x3f, 0xef, 0xf8, 0xec, 0x23, 0x75, 0x84, 0x31, 0xb8, 0x81, 0x82, 0x90, 0x8d, 0x93, 0x17,
	0x75, 0xe3, 0x73, 0x84, 0x1a, 0xe2, 0x6c, 0x46, 0xf9, 0x20, 0x25, 0xff, 0x82, 0x76, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x7a, 0x6f, 0x83, 0x1d, 0xf8, 0x04, 0x00, 0x00,
}

func (m *Epoch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Epoch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Epoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TssInfo) > 0 {
		for iNdEx := len(m.TssInfo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TssInfo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEpoch(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.TssThreshold != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.TssThreshold))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Parties) > 0 {
		for iNdEx := len(m.Parties) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Parties[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEpoch(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.EndBlock != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.EndBlock))
		i--
		dAtA[i] = 0x20
	}
	if m.StartBlock != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.Status != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EpochSignature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochSignature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochSignature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		{
			size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEpoch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintEpoch(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EpochId != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.EpochId))
		i--
		dAtA[i] = 0x10
	}
	if m.Mod != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.Mod))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EpochSignatureData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochSignatureData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochSignatureData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintEpoch(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0x22
	}
	if m.EndTime != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.EndTime))
		i--
		dAtA[i] = 0x18
	}
	if m.StartTime != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.StartTime))
		i--
		dAtA[i] = 0x10
	}
	if len(m.NewSigner) > 0 {
		i -= len(m.NewSigner)
		copy(dAtA[i:], m.NewSigner)
		i = encodeVarintEpoch(dAtA, i, uint64(len(m.NewSigner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochChainSignatures) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochChainSignatures) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochChainSignatures) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RemovedSignature != nil {
		{
			size, err := m.RemovedSignature.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEpoch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.AddedSignature != nil {
		{
			size, err := m.AddedSignature.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEpoch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintEpoch(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if m.EpochId != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.EpochId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TSSInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TSSInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TSSInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEpoch(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Domen) > 0 {
		i -= len(m.Domen)
		copy(dAtA[i:], m.Domen)
		i = encodeVarintEpoch(dAtA, i, uint64(len(m.Domen)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Certification) > 0 {
		i -= len(m.Certification)
		copy(dAtA[i:], m.Certification)
		i = encodeVarintEpoch(dAtA, i, uint64(len(m.Certification)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEpoch(dAtA []byte, offset int, v uint64) int {
	offset -= sovEpoch(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Epoch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovEpoch(uint64(m.Id))
	}
	if m.Status != 0 {
		n += 1 + sovEpoch(uint64(m.Status))
	}
	if m.StartBlock != 0 {
		n += 1 + sovEpoch(uint64(m.StartBlock))
	}
	if m.EndBlock != 0 {
		n += 1 + sovEpoch(uint64(m.EndBlock))
	}
	if len(m.Parties) > 0 {
		for _, e := range m.Parties {
			l = e.Size()
			n += 1 + l + sovEpoch(uint64(l))
		}
	}
	if m.TssThreshold != 0 {
		n += 1 + sovEpoch(uint64(m.TssThreshold))
	}
	if len(m.TssInfo) > 0 {
		for _, e := range m.TssInfo {
			l = e.Size()
			n += 1 + l + sovEpoch(uint64(l))
		}
	}
	return n
}

func (m *EpochSignature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Mod != 0 {
		n += 1 + sovEpoch(uint64(m.Mod))
	}
	if m.EpochId != 0 {
		n += 1 + sovEpoch(uint64(m.EpochId))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovEpoch(uint64(l))
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovEpoch(uint64(l))
	}
	return n
}

func (m *EpochSignatureData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NewSigner)
	if l > 0 {
		n += 1 + l + sovEpoch(uint64(l))
	}
	if m.StartTime != 0 {
		n += 1 + sovEpoch(uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		n += 1 + sovEpoch(uint64(m.EndTime))
	}
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovEpoch(uint64(l))
	}
	return n
}

func (m *EpochChainSignatures) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochId != 0 {
		n += 1 + sovEpoch(uint64(m.EpochId))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovEpoch(uint64(l))
	}
	if m.AddedSignature != nil {
		l = m.AddedSignature.Size()
		n += 1 + l + sovEpoch(uint64(l))
	}
	if m.RemovedSignature != nil {
		l = m.RemovedSignature.Size()
		n += 1 + l + sovEpoch(uint64(l))
	}
	return n
}

func (m *TSSInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Certification)
	if l > 0 {
		n += 1 + l + sovEpoch(uint64(l))
	}
	l = len(m.Domen)
	if l > 0 {
		n += 1 + l + sovEpoch(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEpoch(uint64(l))
	}
	if m.Active {
		n += 2
	}
	return n
}

func sovEpoch(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEpoch(x uint64) (n int) {
	return sovEpoch(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Epoch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpoch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Epoch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Epoch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= EpochStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlock", wireType)
			}
			m.EndBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parties", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Parties = append(m.Parties, &Party{})
			if err := m.Parties[len(m.Parties)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TssThreshold", wireType)
			}
			m.TssThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TssThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TssInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TssInfo = append(m.TssInfo, TSSInfo{})
			if err := m.TssInfo[len(m.TssInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEpoch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpoch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochSignature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpoch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochSignature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochSignature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mod", wireType)
			}
			m.Mod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mod |= EpochSignatureMod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochId", wireType)
			}
			m.EpochId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &EpochSignatureData{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEpoch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpoch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochSignatureData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpoch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochSignatureData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochSignatureData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewSigner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewSigner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEpoch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpoch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochChainSignatures) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpoch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochChainSignatures: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochChainSignatures: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochId", wireType)
			}
			m.EpochId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddedSignature", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AddedSignature == nil {
				m.AddedSignature = &EpochSignature{}
			}
			if err := m.AddedSignature.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemovedSignature", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RemovedSignature == nil {
				m.RemovedSignature = &EpochSignature{}
			}
			if err := m.RemovedSignature.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEpoch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpoch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TSSInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpoch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TSSInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TSSInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certification", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certification = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domen", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domen = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEpoch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpoch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEpoch(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEpoch
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEpoch
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEpoch
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEpoch
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEpoch        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEpoch          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEpoch = fmt.Errorf("proto: unexpected end of group")
)
