// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/models/epoch.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Epoch struct {
	Id           uint64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartBlock   int64                    `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock     int64                    `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	Transactions []*TransactionIdentifier `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (m *Epoch) Reset()         { *m = Epoch{} }
func (m *Epoch) String() string { return proto.CompactTextString(m) }
func (*Epoch) ProtoMessage()    {}
func (*Epoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea792eb5bd367833, []int{0}
}
func (m *Epoch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Epoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Epoch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Epoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Epoch.Merge(m, src)
}
func (m *Epoch) XXX_Size() int {
	return m.Size()
}
func (m *Epoch) XXX_DiscardUnknown() {
	xxx_messageInfo_Epoch.DiscardUnknown(m)
}

var xxx_messageInfo_Epoch proto.InternalMessageInfo

func (m *Epoch) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Epoch) GetStartBlock() int64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *Epoch) GetEndBlock() int64 {
	if m != nil {
		return m.EndBlock
	}
	return 0
}

func (m *Epoch) GetTransactions() []*TransactionIdentifier {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Epoch)(nil), "core.bridge.Epoch")
}

func init() { proto.RegisterFile("bridge/models/epoch.proto", fileDescriptor_ea792eb5bd367833) }

var fileDescriptor_ea792eb5bd367833 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4e, 0x32, 0x31,
	0x10, 0xc7, 0x59, 0xe0, 0xfb, 0xa2, 0x8b, 0xf1, 0xb0, 0xf1, 0x00, 0x68, 0x16, 0xc2, 0x89, 0x98,
	0xb8, 0x13, 0xf0, 0x05, 0x0c, 0x89, 0x26, 0xde, 0x0c, 0xf1, 0xc4, 0xc5, 0xb4, 0xdb, 0xa1, 0x54,
	0x97, 0xce, 0xda, 0x16, 0x22, 0x6f, 0xe1, 0x0b, 0xf8, 0x3e, 0x1e, 0x39, 0x7a, 0x34, 0xf0, 0x22,
	0x66, 0xcb, 0x26, 0xc0, 0xad, 0xf9, 0xfd, 0xfe, 0xfd, 0xcf, 0x64, 0xc2, 0x16, 0x37, 0x4a, 0x48,
	0x84, 0x39, 0x09, 0xcc, 0x2c, 0x60, 0x4e, 0xe9, 0x2c, 0xc9, 0x0d, 0x39, 0x8a, 0x1a, 0x29, 0x19,
	0x4c, 0x76, 0xbe, 0xdd, 0x92, 0x44, 0x32, 0x43, 0xf0, 0x8a, 0x2f, 0xa6, 0xc0, 0xf4, 0x6a, 0x97,
	0x6b, 0x5f, 0xa7, 0x64, 0xe7, 0x64, 0x81, 0x33, 0x8b, 0xf0, 0xbe, 0x40, 0xb3, 0x82, 0xe5, 0x80,
	0xa3, 0x63, 0x03, 0xc8, 0x99, 0x54, 0x9a, 0x39, 0x45, 0xba, 0xcc, 0x5e, 0x95, 0x35, 0x2c, 0x57,
	0xc0, 0xb4, 0x26, 0xe7, 0xa5, 0x2d, 0xed, 0x85, 0x24, 0x49, 0xfe, 0x09, 0xc5, 0xab, 0xa4, 0x9d,
	0xe3, 0x15, 0x9d, 0x61, 0xda, 0xb2, 0x74, 0x5f, 0xda, 0xfb, 0x0a, 0xc2, 0x7f, 0xf7, 0xc5, 0xe2,
	0xd1, 0x79, 0x58, 0x55, 0xa2, 0x19, 0x74, 0x83, 0x7e, 0x7d, 0x5c, 0x55, 0x22, 0xea, 0x84, 0x0d,
	0xeb, 0x98, 0x71, 0x2f, 0x3c, 0xa3, 0xf4, 0xad, 0x59, 0xed, 0x06, 0xfd, 0xda, 0x38, 0xf4, 0x68,
	0x54, 0x90, 0xe8, 0x32, 0x3c, 0x45, 0x2d, 0x4a, 0x5d, 0xf3, 0xfa, 0x04, 0xb5, 0xd8, 0xc9, 0x87,
	0xf0, 0xec, 0x60, 0x98, 0x6d, 0xd6, 0xbb, 0xb5, 0x7e, 0x63, 0xd8, 0x4b, 0x0e, 0xee, 0x92, 0x3c,
	0xef, 0x03, 0x8f, 0x02, 0xb5, 0x53, 0x53, 0x85, 0x66, 0x7c, 0xf4, 0x6f, 0x34, 0xf9, 0xde, 0xc4,
	0xc1, 0x7a, 0x13, 0x07, 0xbf, 0x9b, 0x38, 0xf8, 0xdc, 0xc6, 0x95, 0xf5, 0x36, 0xae, 0xfc, 0x6c,
	0xe3, 0xca, 0xe4, 0x4e, 0x2a, 0x37, 0x5b, 0xf0, 0x24, 0xa5, 0x39, 0x8c, 0x7c, 0x61, 0x86, 0xd6,
	0xde, 0x3c, 0x19, 0x7a, 0xc5, 0xd4, 0x01, 0xdf, 0xa3, 0x62, 0x26, 0x2c, 0x07, 0x43, 0xf8, 0x28,
	0x29, 0xb8, 0x55, 0x8e, 0x96, 0xff, 0xf7, 0x27, 0xb8, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x82,
	0x4a, 0x95, 0x2c, 0xc8, 0x01, 0x00, 0x00,
}

func (m *Epoch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Epoch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Epoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for iNdEx := len(m.Transactions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Transactions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEpoch(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.EndBlock != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.EndBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.StartBlock != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintEpoch(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEpoch(dAtA []byte, offset int, v uint64) int {
	offset -= sovEpoch(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Epoch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovEpoch(uint64(m.Id))
	}
	if m.StartBlock != 0 {
		n += 1 + sovEpoch(uint64(m.StartBlock))
	}
	if m.EndBlock != 0 {
		n += 1 + sovEpoch(uint64(m.EndBlock))
	}
	if len(m.Transactions) > 0 {
		for _, e := range m.Transactions {
			l = e.Size()
			n += 1 + l + sovEpoch(uint64(l))
		}
	}
	return n
}

func sovEpoch(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEpoch(x uint64) (n int) {
	return sovEpoch(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Epoch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpoch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Epoch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Epoch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlock", wireType)
			}
			m.EndBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, &TransactionIdentifier{})
			if err := m.Transactions[len(m.Transactions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEpoch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpoch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEpoch(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEpoch
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpoch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEpoch
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEpoch
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEpoch
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEpoch        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEpoch          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEpoch = fmt.Errorf("proto: unexpected end of group")
)
