// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	ModuleAdmin     string   `protobuf:"bytes,1,opt,name=module_admin,json=moduleAdmin,proto3" json:"module_admin,omitempty"`
	Parties         []*Party `protobuf:"bytes,2,rep,name=parties,proto3" json:"parties,omitempty"`
	TssThreshold    uint32   `protobuf:"varint,3,opt,name=tss_threshold,json=tssThreshold,proto3" json:"tss_threshold,omitempty"`
	RelayerAccounts []string `protobuf:"bytes,4,rep,name=relayer_accounts,json=relayerAccounts,proto3" json:"relayer_accounts,omitempty"`
	EpochSequence   uint64   `protobuf:"varint,5,opt,name=epoch_sequence,json=epochSequence,proto3" json:"epoch_sequence,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed6fb968a083dd73, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetModuleAdmin() string {
	if m != nil {
		return m.ModuleAdmin
	}
	return ""
}

func (m *Params) GetParties() []*Party {
	if m != nil {
		return m.Parties
	}
	return nil
}

func (m *Params) GetTssThreshold() uint32 {
	if m != nil {
		return m.TssThreshold
	}
	return 0
}

func (m *Params) GetRelayerAccounts() []string {
	if m != nil {
		return m.RelayerAccounts
	}
	return nil
}

func (m *Params) GetEpochSequence() uint64 {
	if m != nil {
		return m.EpochSequence
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "core.bridge.Params")
}

func init() { proto.RegisterFile("bridge/params.proto", fileDescriptor_ed6fb968a083dd73) }

var fileDescriptor_ed6fb968a083dd73 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0xe0, 0x9a, 0x96, 0xa2, 0xba, 0x2d, 0x20, 0xc3, 0x10, 0x3a, 0x44, 0x01, 0x84, 0x14,
	0x24, 0x88, 0x45, 0x79, 0x01, 0xda, 0x27, 0xa8, 0x02, 0x53, 0x97, 0x28, 0x71, 0x4e, 0x49, 0x50,
	0x52, 0x07, 0x9f, 0x83, 0xe8, 0x5b, 0xf0, 0x58, 0x8c, 0x1d, 0x19, 0x51, 0xfb, 0x22, 0xc8, 0x49,
	0x2a, 0xd8, 0xac, 0xef, 0xee, 0x3f, 0xdb, 0x47, 0xcf, 0x22, 0x95, 0xc5, 0x09, 0xf0, 0x32, 0x54,
	0x61, 0x81, 0x5e, 0xa9, 0xa4, 0x96, 0x6c, 0x28, 0xa4, 0x02, 0xaf, 0xa9, 0x4c, 0xce, 0x13, 0x99,
	0xc8, 0xda, 0xb9, 0x39, 0x35, 0x2d, 0x93, 0x8b, 0x36, 0x57, 0xc8, 0x18, 0x72, 0x34, 0x71, 0xbd,
	0x6e, 0x4a, 0x57, 0x1b, 0x42, 0xfb, 0x8b, 0x7a, 0x1c, 0xbb, 0xa4, 0xa3, 0x42, 0xc6, 0x55, 0x0e,
	0x41, 0x18, 0x17, 0xd9, 0xca, 0x22, 0x0e, 0x71, 0x07, 0xfe, 0xb0, 0xb1, 0x99, 0x21, 0x76, 0x47,
	0x8f, 0x4c, 0x38, 0x03, 0xb4, 0x0e, 0x9c, 0xae, 0x3b, 0x9c, 0x32, 0xef, 0xdf, 0xed, 0xde, 0xc2,
	0x0c, 0xf6, 0xf7, 0x2d, 0xec, 0x9a, 0x8e, 0x35, 0x62, 0xa0, 0x53, 0x05, 0x98, 0xca, 0x3c, 0xb6,
	0xba, 0x0e, 0x71, 0xc7, 0xfe, 0x48, 0x23, 0xbe, 0xec, 0x8d, 0xdd, 0xd2, 0x53, 0x05, 0x79, 0xb8,
	0x06, 0x15, 0x84, 0x42, 0xc8, 0x6a, 0xa5, 0xd1, 0xea, 0x39, 0x5d, 0x77, 0xe0, 0x9f, 0xb4, 0x3e,
	0x6b, 0x99, 0xdd, 0xd0, 0x63, 0x28, 0xa5, 0x48, 0x03, 0x84, 0xb7, 0x0a, 0x56, 0x02, 0xac, 0x43,
	0x87, 0xb8, 0x3d, 0x7f, 0x5c, 0xeb, 0x73, 0x8b, 0xf3, 0xe5, 0xd7, 0xd6, 0x26, 0x9b, 0xad, 0x4d,
	0x7e, 0xb6, 0x36, 0xf9, 0xdc, 0xd9, 0x9d, 0xcd, 0xce, 0xee, 0x7c, 0xef, 0xec, 0xce, 0xf2, 0x29,
	0xc9, 0x74, 0x5a, 0x45, 0x9e, 0x90, 0x05, 0x9f, 0xd7, 0x4f, 0xce, 0x01, 0xf1, 0x7e, 0xa1, 0xe4,
	0x2b, 0x08, 0xcd, 0xa3, 0x3f, 0x32, 0xbf, 0xe2, 0xef, 0x0f, 0x53, 0xfe, 0xd1, 0x2a, 0xd7, 0xeb,
	0x12, 0x30, 0xea, 0xd7, 0x5b, 0x7b, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x08, 0x75, 0xed, 0xc5,
	0x8a, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochSequence != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochSequence))
		i--
		dAtA[i] = 0x28
	}
	if len(m.RelayerAccounts) > 0 {
		for iNdEx := len(m.RelayerAccounts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RelayerAccounts[iNdEx])
			copy(dAtA[i:], m.RelayerAccounts[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.RelayerAccounts[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.TssThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TssThreshold))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Parties) > 0 {
		for iNdEx := len(m.Parties) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Parties[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ModuleAdmin) > 0 {
		i -= len(m.ModuleAdmin)
		copy(dAtA[i:], m.ModuleAdmin)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ModuleAdmin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModuleAdmin)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.Parties) > 0 {
		for _, e := range m.Parties {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.TssThreshold != 0 {
		n += 1 + sovParams(uint64(m.TssThreshold))
	}
	if len(m.RelayerAccounts) > 0 {
		for _, s := range m.RelayerAccounts {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.EpochSequence != 0 {
		n += 1 + sovParams(uint64(m.EpochSequence))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleAdmin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parties", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Parties = append(m.Parties, &Party{})
			if err := m.Parties[len(m.Parties)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TssThreshold", wireType)
			}
			m.TssThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TssThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerAccounts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayerAccounts = append(m.RelayerAccounts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochSequence", wireType)
			}
			m.EpochSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
