// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: swap/models/transaction.proto

package types

import (
	fmt "fmt"
	types "github.com/Bridgeless-Project/bridgeless-core/v12/x/bridge/types"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SwapTransaction struct {
	Tx                 types.Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx"`
	FinalReceiver      string            `protobuf:"bytes,2,opt,name=final_receiver,json=finalReceiver,proto3" json:"final_receiver,omitempty"`
	FinalToken         string            `protobuf:"bytes,3,opt,name=final_token,json=finalToken,proto3" json:"final_token,omitempty"`
	FinalChainId       string            `protobuf:"bytes,4,opt,name=final_chain_id,json=finalChainId,proto3" json:"final_chain_id,omitempty"`
	SwapDeadline       uint64            `protobuf:"varint,5,opt,name=swap_deadline,json=swapDeadline,proto3" json:"swap_deadline,omitempty"`
	SwapOutAmount      string            `protobuf:"bytes,6,opt,name=swap_out_amount,json=swapOutAmount,proto3" json:"swap_out_amount,omitempty"`
	FinalDepositTxHash string            `protobuf:"bytes,7,opt,name=final_deposit_tx_hash,json=finalDepositTxHash,proto3" json:"final_deposit_tx_hash,omitempty"`
	IsFeeDistribution  bool              `protobuf:"varint,8,opt,name=is_fee_distribution,json=isFeeDistribution,proto3" json:"is_fee_distribution,omitempty"`
}

func (m *SwapTransaction) Reset()         { *m = SwapTransaction{} }
func (m *SwapTransaction) String() string { return proto.CompactTextString(m) }
func (*SwapTransaction) ProtoMessage()    {}
func (*SwapTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e4b1b07dbb5aa1d, []int{0}
}
func (m *SwapTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SwapTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SwapTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SwapTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapTransaction.Merge(m, src)
}
func (m *SwapTransaction) XXX_Size() int {
	return m.Size()
}
func (m *SwapTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SwapTransaction proto.InternalMessageInfo

func (m *SwapTransaction) GetTx() types.Transaction {
	if m != nil {
		return m.Tx
	}
	return types.Transaction{}
}

func (m *SwapTransaction) GetFinalReceiver() string {
	if m != nil {
		return m.FinalReceiver
	}
	return ""
}

func (m *SwapTransaction) GetFinalToken() string {
	if m != nil {
		return m.FinalToken
	}
	return ""
}

func (m *SwapTransaction) GetFinalChainId() string {
	if m != nil {
		return m.FinalChainId
	}
	return ""
}

func (m *SwapTransaction) GetSwapDeadline() uint64 {
	if m != nil {
		return m.SwapDeadline
	}
	return 0
}

func (m *SwapTransaction) GetSwapOutAmount() string {
	if m != nil {
		return m.SwapOutAmount
	}
	return ""
}

func (m *SwapTransaction) GetFinalDepositTxHash() string {
	if m != nil {
		return m.FinalDepositTxHash
	}
	return ""
}

func (m *SwapTransaction) GetIsFeeDistribution() bool {
	if m != nil {
		return m.IsFeeDistribution
	}
	return false
}

func init() {
	proto.RegisterType((*SwapTransaction)(nil), "core.swap.SwapTransaction")
}

func init() { proto.RegisterFile("swap/models/transaction.proto", fileDescriptor_6e4b1b07dbb5aa1d) }

var fileDescriptor_6e4b1b07dbb5aa1d = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0x87, 0xe3, 0x10, 0x4a, 0xbb, 0x6d, 0xa9, 0x58, 0x40, 0x5a, 0x2a, 0x70, 0x22, 0xfe, 0x29,
	0x17, 0xbc, 0x6a, 0xb9, 0x23, 0x11, 0x22, 0x04, 0x27, 0x90, 0xc9, 0x01, 0x71, 0xb1, 0xd6, 0xf6,
	0xc4, 0x5e, 0x70, 0x76, 0xad, 0xdd, 0x71, 0xeb, 0xbe, 0x05, 0x8f, 0xd5, 0x63, 0x8f, 0x9c, 0x00,
	0x25, 0x2f, 0x82, 0x76, 0x6d, 0xd4, 0x5c, 0x7a, 0x5b, 0x7d, 0xbf, 0x4f, 0x33, 0xa3, 0x99, 0x25,
	0x4f, 0xec, 0xb9, 0xa8, 0xf9, 0x4a, 0xe7, 0x50, 0x59, 0x8e, 0x46, 0x28, 0x2b, 0x32, 0x94, 0x5a,
	0x45, 0xb5, 0xd1, 0xa8, 0xe9, 0x5e, 0xa6, 0x0d, 0x44, 0xce, 0x39, 0x7e, 0x54, 0x68, 0x5d, 0x54,
	0xc0, 0x7d, 0x90, 0x36, 0x4b, 0x2e, 0xd4, 0x45, 0x67, 0x1d, 0x3f, 0xee, 0x23, 0x51, 0x4b, 0x2e,
	0x94, 0xd2, 0x28, 0x5c, 0x09, 0xdb, 0xa7, 0x0f, 0x0a, 0x5d, 0x68, 0xff, 0xe4, 0xee, 0xd5, 0xd3,
	0x71, 0x6a, 0x64, 0x5e, 0xc0, 0x8d, 0xad, 0x9f, 0xfe, 0x19, 0x92, 0xa3, 0x2f, 0xe7, 0xa2, 0x5e,
	0x5c, 0x27, 0x34, 0x22, 0x43, 0x6c, 0x59, 0x30, 0x09, 0xa6, 0xfb, 0xa7, 0x2c, 0xf2, 0xb3, 0x75,
	0x65, 0xa2, 0x2d, 0x6b, 0x36, 0xba, 0xfc, 0x3d, 0x1e, 0xc4, 0x43, 0x6c, 0xe9, 0x0b, 0x72, 0x77,
	0x29, 0x95, 0xa8, 0x12, 0x03, 0x19, 0xc8, 0x33, 0x30, 0x6c, 0x38, 0x09, 0xa6, 0x7b, 0xf1, 0xa1,
	0xa7, 0x71, 0x0f, 0xe9, 0x98, 0xec, 0x77, 0x1a, 0xea, 0x1f, 0xa0, 0xd8, 0x2d, 0xef, 0x10, 0x8f,
	0x16, 0x8e, 0xd0, 0xe7, 0xff, 0xeb, 0x64, 0xa5, 0x90, 0x2a, 0x91, 0x39, 0x1b, 0x79, 0xe7, 0xc0,
	0xd3, 0x77, 0x0e, 0x7e, 0xcc, 0xe9, 0x33, 0x72, 0xe8, 0x36, 0x95, 0xe4, 0x20, 0xf2, 0x4a, 0x2a,
	0x60, 0xb7, 0x27, 0xc1, 0x74, 0x14, 0x1f, 0x38, 0x38, 0xef, 0x19, 0x7d, 0x49, 0x8e, 0xbc, 0xa4,
	0x1b, 0x4c, 0xc4, 0x4a, 0x37, 0x0a, 0xd9, 0x4e, 0x37, 0x93, 0xc3, 0x9f, 0x1a, 0x7c, 0xeb, 0x21,
	0x3d, 0x21, 0x0f, 0xbb, 0x96, 0x39, 0xd4, 0xda, 0x4a, 0x4c, 0xb0, 0x4d, 0x4a, 0x61, 0x4b, 0x76,
	0xc7, 0xdb, 0xd4, 0x87, 0xf3, 0x2e, 0x5b, 0xb4, 0x1f, 0x84, 0x2d, 0x69, 0x44, 0xee, 0x4b, 0x9b,
	0x2c, 0x01, 0x92, 0x5c, 0x5a, 0x34, 0x32, 0x6d, 0xdc, 0x3a, 0xd8, 0xee, 0x24, 0x98, 0xee, 0xc6,
	0xf7, 0xa4, 0x7d, 0x0f, 0x30, 0xdf, 0x0a, 0x66, 0x5f, 0x2f, 0xd7, 0x61, 0x70, 0xb5, 0x0e, 0x83,
	0xbf, 0xeb, 0x30, 0xf8, 0xb9, 0x09, 0x07, 0x57, 0x9b, 0x70, 0xf0, 0x6b, 0x13, 0x0e, 0xbe, 0xbd,
	0x29, 0x24, 0x96, 0x4d, 0x1a, 0x65, 0x7a, 0xc5, 0x67, 0x7e, 0xc1, 0x15, 0x58, 0xfb, 0xea, 0xb3,
	0xd1, 0xdf, 0x21, 0x43, 0x9e, 0x5e, 0x23, 0x77, 0x03, 0x7e, 0x76, 0x72, 0xca, 0x5b, 0xee, 0x7f,
	0x12, 0x5e, 0xd4, 0x60, 0xd3, 0x1d, 0x7f, 0xc2, 0xd7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2d,
	0xd1, 0x2f, 0x18, 0x5e, 0x02, 0x00, 0x00,
}

func (m *SwapTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwapTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SwapTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsFeeDistribution {
		i--
		if m.IsFeeDistribution {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.FinalDepositTxHash) > 0 {
		i -= len(m.FinalDepositTxHash)
		copy(dAtA[i:], m.FinalDepositTxHash)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.FinalDepositTxHash)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SwapOutAmount) > 0 {
		i -= len(m.SwapOutAmount)
		copy(dAtA[i:], m.SwapOutAmount)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.SwapOutAmount)))
		i--
		dAtA[i] = 0x32
	}
	if m.SwapDeadline != 0 {
		i = encodeVarintTransaction(dAtA, i, uint64(m.SwapDeadline))
		i--
		dAtA[i] = 0x28
	}
	if len(m.FinalChainId) > 0 {
		i -= len(m.FinalChainId)
		copy(dAtA[i:], m.FinalChainId)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.FinalChainId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FinalToken) > 0 {
		i -= len(m.FinalToken)
		copy(dAtA[i:], m.FinalToken)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.FinalToken)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FinalReceiver) > 0 {
		i -= len(m.FinalReceiver)
		copy(dAtA[i:], m.FinalReceiver)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.FinalReceiver)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTransaction(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTransaction(dAtA []byte, offset int, v uint64) int {
	offset -= sovTransaction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SwapTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Tx.Size()
	n += 1 + l + sovTransaction(uint64(l))
	l = len(m.FinalReceiver)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.FinalToken)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.FinalChainId)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	if m.SwapDeadline != 0 {
		n += 1 + sovTransaction(uint64(m.SwapDeadline))
	}
	l = len(m.SwapOutAmount)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.FinalDepositTxHash)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	if m.IsFeeDistribution {
		n += 2
	}
	return n
}

func sovTransaction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTransaction(x uint64) (n int) {
	return sovTransaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SwapTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwapTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwapTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalReceiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalReceiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapDeadline", wireType)
			}
			m.SwapDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SwapDeadline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapOutAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapOutAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalDepositTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalDepositTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsFeeDistribution", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsFeeDistribution = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTransaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTransaction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTransaction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTransaction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTransaction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTransaction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTransaction = fmt.Errorf("proto: unexpected end of group")
)
