// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: swap/models/transaction.proto

package types

import (
	fmt "fmt"
	types "github.com/Bridgeless-Project/bridgeless-core/v12/x/bridge/types"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SwapTransaction struct {
	Tx                 types.Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx"`
	FinalReceiver      string            `protobuf:"bytes,2,opt,name=final_receiver,json=finalReceiver,proto3" json:"final_receiver,omitempty"`
	FinalAmount        string            `protobuf:"bytes,3,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	AmountOutMin       string            `protobuf:"bytes,4,opt,name=amount_out_min,json=amountOutMin,proto3" json:"amount_out_min,omitempty"`
	FinalDepositTxHash string            `protobuf:"bytes,5,opt,name=final_deposit_tx_hash,json=finalDepositTxHash,proto3" json:"final_deposit_tx_hash,omitempty"`
}

func (m *SwapTransaction) Reset()         { *m = SwapTransaction{} }
func (m *SwapTransaction) String() string { return proto.CompactTextString(m) }
func (*SwapTransaction) ProtoMessage()    {}
func (*SwapTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e4b1b07dbb5aa1d, []int{0}
}
func (m *SwapTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SwapTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SwapTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SwapTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapTransaction.Merge(m, src)
}
func (m *SwapTransaction) XXX_Size() int {
	return m.Size()
}
func (m *SwapTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SwapTransaction proto.InternalMessageInfo

func (m *SwapTransaction) GetTx() types.Transaction {
	if m != nil {
		return m.Tx
	}
	return types.Transaction{}
}

func (m *SwapTransaction) GetFinalReceiver() string {
	if m != nil {
		return m.FinalReceiver
	}
	return ""
}

func (m *SwapTransaction) GetFinalAmount() string {
	if m != nil {
		return m.FinalAmount
	}
	return ""
}

func (m *SwapTransaction) GetAmountOutMin() string {
	if m != nil {
		return m.AmountOutMin
	}
	return ""
}

func (m *SwapTransaction) GetFinalDepositTxHash() string {
	if m != nil {
		return m.FinalDepositTxHash
	}
	return ""
}

func init() {
	proto.RegisterType((*SwapTransaction)(nil), "core.swap.SwapTransaction")
}

func init() { proto.RegisterFile("swap/models/transaction.proto", fileDescriptor_6e4b1b07dbb5aa1d) }

var fileDescriptor_6e4b1b07dbb5aa1d = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0x25, 0xd7, 0x2d, 0x58, 0x76, 0x5d, 0x10, 0x2d, 0xa8, 0xa6, 0x95, 0xdd, 0xd2, 0x82,
	0x09, 0x44, 0x8b, 0x9c, 0x7b, 0x20, 0x26, 0x87, 0x5c, 0x42, 0x82, 0xe3, 0x43, 0xc8, 0x45, 0xac,
	0xe4, 0xb5, 0xb4, 0x41, 0xda, 0x51, 0x76, 0x47, 0xb6, 0xfc, 0x16, 0x79, 0x2c, 0x1f, 0x7d, 0xcc,
	0x29, 0x04, 0x3b, 0x0f, 0x12, 0xbc, 0x12, 0x38, 0x97, 0xdc, 0x86, 0xff, 0xfb, 0xf8, 0xd9, 0x99,
	0xb5, 0x7e, 0xab, 0x25, 0xcd, 0x49, 0x06, 0x33, 0x96, 0x2a, 0x82, 0x92, 0x0a, 0x45, 0x23, 0xe4,
	0x20, 0xbc, 0x5c, 0x02, 0x82, 0xdd, 0x8a, 0x40, 0x32, 0x6f, 0xef, 0xf4, 0x7e, 0xc6, 0x00, 0x71,
	0xca, 0x88, 0x06, 0x61, 0x31, 0x27, 0x54, 0xac, 0x2a, 0xab, 0x77, 0x14, 0x81, 0xca, 0x40, 0x91,
	0x90, 0x2a, 0x46, 0x1e, 0x0a, 0x26, 0x57, 0x64, 0xe1, 0x87, 0x0c, 0xa9, 0x4f, 0x72, 0x1a, 0x73,
	0x41, 0x0f, 0x8d, 0xbd, 0x5f, 0x75, 0x0d, 0xcd, 0x39, 0xa1, 0x42, 0x00, 0x6a, 0xa8, 0x6a, 0xfa,
	0x3d, 0x86, 0x18, 0xf4, 0x48, 0xf6, 0x53, 0x9d, 0xf6, 0x43, 0xc9, 0x67, 0x31, 0xfb, 0xf0, 0x99,
	0x7f, 0x5f, 0x4d, 0xeb, 0xdb, 0xcd, 0x92, 0xe6, 0xd3, 0x03, 0xb1, 0x3d, 0xab, 0x81, 0xa5, 0x63,
	0x0e, 0xcc, 0x61, 0x7b, 0xe4, 0x78, 0x7a, 0x8f, 0xaa, 0xc6, 0x7b, 0x67, 0x8d, 0x9b, 0xeb, 0xe7,
	0xbe, 0x31, 0x69, 0x60, 0x69, 0xff, 0xb7, 0xba, 0x73, 0x2e, 0x68, 0x1a, 0x48, 0x16, 0x31, 0xbe,
	0x60, 0xd2, 0x69, 0x0c, 0xcc, 0x61, 0x6b, 0xf2, 0x55, 0xa7, 0x93, 0x3a, 0xb4, 0xff, 0x58, 0x9d,
	0x4a, 0xa3, 0x19, 0x14, 0x02, 0x9d, 0x4f, 0x5a, 0x6a, 0xeb, 0xec, 0x4c, 0x47, 0xf6, 0x3f, 0xab,
	0x5b, 0xc1, 0x00, 0x0a, 0x0c, 0x32, 0x2e, 0x9c, 0xa6, 0x96, 0x3a, 0x55, 0x7a, 0x55, 0xe0, 0x25,
	0x17, 0xb6, 0x6f, 0xfd, 0xa8, 0x8a, 0x66, 0x2c, 0x07, 0xc5, 0x31, 0xc0, 0x32, 0x48, 0xa8, 0x4a,
	0x9c, 0xcf, 0x5a, 0xb6, 0x35, 0x3c, 0xaf, 0xd8, 0xb4, 0xbc, 0xa0, 0x2a, 0x19, 0xdf, 0xae, 0xb7,
	0xae, 0xb9, 0xd9, 0xba, 0xe6, 0xcb, 0xd6, 0x35, 0x1f, 0x77, 0xae, 0xb1, 0xd9, 0xb9, 0xc6, 0xd3,
	0xce, 0x35, 0xee, 0x4e, 0x63, 0x8e, 0x49, 0x11, 0x7a, 0x11, 0x64, 0x64, 0xac, 0xb7, 0x4c, 0x99,
	0x52, 0xc7, 0xd7, 0x12, 0xee, 0x59, 0x84, 0x24, 0x3c, 0x44, 0xfb, 0x43, 0x90, 0x85, 0x3f, 0x22,
	0x25, 0xd1, 0x5f, 0x8f, 0xab, 0x9c, 0xa9, 0xf0, 0x8b, 0xbe, 0xe3, 0xc9, 0x5b, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x11, 0x52, 0x31, 0x3c, 0x0f, 0x02, 0x00, 0x00,
}

func (m *SwapTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwapTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SwapTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FinalDepositTxHash) > 0 {
		i -= len(m.FinalDepositTxHash)
		copy(dAtA[i:], m.FinalDepositTxHash)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.FinalDepositTxHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AmountOutMin) > 0 {
		i -= len(m.AmountOutMin)
		copy(dAtA[i:], m.AmountOutMin)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.AmountOutMin)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FinalAmount) > 0 {
		i -= len(m.FinalAmount)
		copy(dAtA[i:], m.FinalAmount)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.FinalAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FinalReceiver) > 0 {
		i -= len(m.FinalReceiver)
		copy(dAtA[i:], m.FinalReceiver)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.FinalReceiver)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTransaction(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTransaction(dAtA []byte, offset int, v uint64) int {
	offset -= sovTransaction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SwapTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Tx.Size()
	n += 1 + l + sovTransaction(uint64(l))
	l = len(m.FinalReceiver)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.FinalAmount)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.AmountOutMin)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.FinalDepositTxHash)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	return n
}

func sovTransaction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTransaction(x uint64) (n int) {
	return sovTransaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SwapTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwapTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwapTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalReceiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalReceiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountOutMin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountOutMin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalDepositTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalDepositTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTransaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTransaction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTransaction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTransaction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTransaction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTransaction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTransaction = fmt.Errorf("proto: unexpected end of group")
)
